# ===================================================================
# UNIFIED APPLICATION CONFIGURATION
# ===================================================================

# Server Configuration
server:
  port: 8080

# Spring Configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:mariadb://localhost:3306/tool_management_db
    username: root
    password: password123
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-version: 0
    validate-on-migrate: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5000

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5 minutes
      use-key-prefix: true
      key-prefix: exec

# Logging Configuration
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG
    viettel.dac.prototype.execution: INFO
    viettel.dac.prototype.llm: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

# Execution Engine Configuration
execution:
  # HTTP Client Configuration
  httpclient:
    connect-timeout: 5000
    read-timeout: 30000
    write-timeout: 30000
    max-in-memory-size: 16777216  # 16MB
    max-retry-attempts: 3
    retry-backoff: 1000

  # Retry Configuration
  retry:
    max-attempts: 3
    initial-backoff: 1000
    max-backoff: 10000
    backoff-multiplier: 2.0

  # Rate Limiting Configuration
  ratelimit:
    limit-for-period: 50
    limit-refresh-period: 1
    timeout-duration: 5

    # Chat API rate limits
    chat:
      limit-for-period: 20
      limit-refresh-period: 1
      timeout-duration: 3

  # Metrics Configuration
  metrics:
    percentiles: 0.5,0.95,0.99
    sla: 100,500,1000,5000

  # Cache Configuration
  cache:
    default-ttl: 300
    dependency-graph-ttl: 3600
    tool-ttl: 600

  # Security Configuration
  security:
    allowed-origins: "*"
    require-ssl: true
    jwt:
      auth-claim: roles
      role-prefix: ROLE_

# Spring Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
  metrics:
    distribution:
      percentiles-histogram:
        execution: true
  prometheus:
    metrics:
      export:
        enabled: true

# LLM Configuration
llm:
  openai:
    model: gpt-4o
    api-key:
  conversation:
    max-history: 10
    ttl-hours: 24

# Add profiles section to enable easy environment switching
---
spring:
  config:
    activate:
      on-profile: dev
  # Development-specific overrides
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false

---
spring:
  config:
    activate:
      on-profile: prod
  # Production-specific overrides
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

# Security is enforced in production
execution:
  security:
    require-ssl: true

# Logging levels for production
logging:
  level:
    root: WARN
    viettel.dac.prototype: INFO
    org.hibernate.SQL: WARN
    org.flywaydb: INFO