version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.6
    container_name: tool-management-db
    environment:
      - MARIADB_ROOT_PASSWORD=password123
      - MARIADB_DATABASE=tool_management_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - tool-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and session management
  redis:
    image: redis:6.2-alpine
    container_name: tool-management-redis
    command: redis-server --requirepass ""
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - tool-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tool-network:
    driver: bridge

volumes:
  mariadb-data:
  redis-data:
